#!/bin/sh
### BEGIN INIT INFO
# Provides:          fix-clock
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Set system clock from HTTP time (no RTC/NTP on this board)
### END INIT INFO

case "$1" in
  start)
    echo "Syncing clock from network time..."
    for i in 1 2 3 4 5 6 7 8 9 10; do
      HTTP_DATE=$(curl -s -I -m 5 http://google.com 2>/dev/null | grep -i '^date:' | sed 's/^[Dd]ate: //;s/\r//')
      if [ -n "$HTTP_DATE" ]; then
        date -s "$HTTP_DATE"
        hwclock -w 2>/dev/null
        echo "Clock set to: $(date)"
        exit 0
      fi
      sleep 2
    done
    echo "fix-clock: could not reach network to sync time, leaving clock as-is"
    ;;
  stop|restart|status)
    ;;
  *)
    echo "Usage: $0 start"
    exit 1
    ;;
esac
exit 0
