#!/bin/sh
### BEGIN INIT INFO
# Provides:          greet-audio-feeder
# Required-Start:    $network fix-clock
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Feeds greeting audio into the live RTSP stream (greet_audio_feeder.py)
### END INIT INFO

NAME=greet-audio-feeder
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/python3
DAEMON_ARGS=-u
SCRIPT=/home/server/sur-floders/greet_audio_feeder.py
LOG=/home/server/sur-floders/logs/greet-audio-feeder.log

start() {
    echo "Starting $NAME..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE \
        --exec /bin/sh -- -c "exec $DAEMON $DAEMON_ARGS $SCRIPT >> $LOG 2>&1"
}

stop() {
    echo "Stopping $NAME..."
    start-stop-daemon --stop --pidfile $PIDFILE --retry 5
    rm -f $PIDFILE
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) stop; sleep 1; start ;;
  status)
    if [ -f $PIDFILE ] && kill -0 "$(cat $PIDFILE)" 2>/dev/null; then
        echo "$NAME is running (pid $(cat $PIDFILE))"
    else
        echo "$NAME is not running"
        exit 1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
exit 0
